spring.application.name=backend

bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000


spring.profiles.active=dev
spring.jpa.open-in-view=true